### ISSUE TITLE
Internal Error 500 - When Steam is down.

### ISSUE THREAD

**Issue by emilkaaekudahl** [Jessecar96/SteamBot#812] opened 2015-09-24 13:44 UTC
When steam is down it gives a internal error 500, and it does not do the thing it should (accept / send offer.) how can I make it do it after the crash? because the bot auto restarts?

**Comment by BlueRaja** [comment] 2015-09-24 14:27
Duplicate of https://github.com/Jessecar96/SteamBot/issues/804

**Closed** 2015-09-24 14:29 UTC
