### ISSUE TITLE
Handling items past 7th december which will be delayed when the trade partner does not have Steam Mobile Auth

### ISSUE THREAD

**Issue by kiapwnz** [Jessecar96/SteamBot#850] opened 2015-11-29 11:18 UTC
Hello there,

Just wanted to ask what possible ways exist (or will exist?) to handle items which we be recieved after the three days delay based on Steam's message:

Starting Dec 9, anyone losing items in a trade will need to have a Steam Guard Mobile Authenticator enabled on their account for at least 7 days. Otherwise, to protect against unauthorized trades, items will be held by Steam for up to 3 days before delivery.

Is it known already what will be called (in the bot) when these items arrive?

**Comment by scholtzm** [comment] 2015-11-29 11:34
Duplicate of https://github.com/Jessecar96/SteamBot/issues/847

**Closed** 2015-11-29 16:47 UTC
